server:
  listen: "[::1]:8080"
logger:
  level: "DEBUG"
  development: true
handlers:
  default_timeout_secs: 60
  handlers_timeouts:
    - method: "GET"
      endpoint: "ping"
      timeout_secs: 120
